travis:
  secure:
    BINSTAR_TOKEN: Ey4yMHPZ4uA7FMNxzktDqD5Q+Fez6wd0alLnLSY4/c17o9D/7xV0iyYMQF8BEs5XByBAnsavGXRX43r/7hY5icJ4madXapdI64Yz3AfHDCxbfFqX5EHt7erasQwz0SDK/5w8xUZl0ZjqrkeygJGeygH61fVJWjIFuf5i6BDNRt9sZwkyKMviVabqB+W2bRNdY8Dwnfb/47uEkDk9HDCRmowIvsl4nhbU9EjIo61xdlbQeFHSv8lfYVUm9tZk+6NXiH3DXaKJXaF6lJWIygknsmcboBej4dhidVS/QFdFS4Ts/JuPBXMM6diF5LQ0Qn6qMZN4gPucJqzq+ox1RaJXLtK5fRfo50LHBU8EaflBh8zzhRZ3LBRNPMh2i6PiXQtMoWaelcDgWFs6fAULClxJgTsryQs4dUXRJvfQtOLVU72G/Y8O0i/ymRT89we4jQfOyes0LId6alRnZepxjU11TiyaBT4MU2qB+7SHqiHDWVoPXNnM3CLm0i1eGlc/Nqo528FgkmnwH15ENhcwtuxQH/JV+UxCa9Aswv3DPV1JyLYRVECdLm7ZdBz8jw1w5I6FcgjA3+6l2PtA+vLNU0yiAr+Ix3usyf/9VMLSM0xKcShncqUm12mMenddQi+R0acBbzzgF6ygDMmVVjoGhWB8RkyYE8g4CSmEYlIszr2fL5s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
