travis:
  secure:
    BINSTAR_TOKEN: kRvWJNGgmrtRNUgT8czz2rN76sSrYrvVnhlBWdnZVk6MY/Nt46MbQ8nMx9O5JFSuTdi+J8xDvO3C6Ji9luEGBRLO5NthwobLk4iIKkalF2jEapcM/nKur2dIVVeis3ezxaX6Dom1yfdWEvT39LujgRpROOhCG2RvsrsZbr1az27Usd6UDFnOYghaVi4Gadu15x+HHn1wwoMFEivGCvOsrsym2qyFqooKvuacb2xhShQ06ohnXvLUaYUtq08Do4it0S81hf5GULuOO8E7LECnMuMMiaiEcyqlbs0sde7EXcp+tFuMbOVoydeWj0rmB8NgRO+0Ng8x3+RdGwwvGZ+s9aGiYduymJz2OD8hJpQdKaepvEoCOxN5Hk/HRE5cpXt+OEZivr0yHb2kz+vzIHmsUVqvHqyNEavkO7BA8i/6vrn44H2awxfeGJc73580NqYCJXZiknXQL6GSEM7P298FLafAfo4MeSRFJE+tSb9zCMOUQ5UT9EAtf7EszSKACaboKRCAQLLE2MwelRcxQkli00wrn34ClY6UR5RyO8hkbb/8sQxvyWird4U7GSbjp4fAyhSiPAWZ9xTDZ/7tall0Ba5pS6Xdb/Pq6weiMQR2PW1hktKngDEJEuGAvILiLuZMtSC+xjw+ThDLylDeSvSy1mKS5pcsuYRAervvFoyIGE0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
